/* NEON APEX: lightweight canvas arcade engine. Add cars/tracks in CONFIG. */
const $ = s => document.querySelector(s);
const canvas = $('#gameCanvas'), ctx = canvas.getContext('2d');
const screens = document.querySelectorAll('.screen');
const CONFIG = {
  cars: [
    {id:'pulse',name:'PULSE GT',desc:'Balanced street machine.',color:'#21d9ff',speed:225,accel:7,handling:7,brake:7,cost:0},
    {id:'vanta',name:'VANTA XR',desc:'Agile midnight striker.',color:'#a98cff',speed:210,accel:8,handling:9,brake:6,cost:180},
    {id:'solar',name:'SOLAR FURY',desc:'Blazing top-end coupe.',color:'#ffb129',speed:255,accel:6,handling:5,brake:6,cost:400},
    {id:'nova',name:'NOVA R-7',desc:'Pure acceleration prototype.',color:'#ff477e',speed:235,accel:10,handling:6,brake:5,cost:750},
    {id:'atlas',name:'ATLAS RALLY',desc:'Stable all-road bruiser.',color:'#57e494',speed:220,accel:6,handling:8,brake:9,cost:1100}
  ],
  tracks: {city:{name:'Neon City',sky:'#1a1640',ground:'#10152b',lights:['#3de8ff','#fb3b8e','#ffc94a']},highway:{name:'Night Highway',sky:'#081424',ground:'#13202b',lights:['#d9eeff','#79bdff']},desert:{name:'Solar Desert',sky:'#5a2140',ground:'#38231f',lights:['#ffba57','#ff6d47']},mountain:{name:'Peak Run',sky:'#142a45',ground:'#192331',lights:['#d9f7ff','#6576ff']}},
  modes:{endless:{label:'ENDLESS RACE'},time:{label:'TIME TRIAL',time:90},challenge:{label:'CHALLENGE',coins:25}}
};
const Store = {data:null,load(){try{this.data=JSON.parse(localStorage.neonApex)||{coins:0,best:0,unlocked:['pulse'],car:'pulse',settings:{sound:true,music:false,graphics:'high'}}}catch{this.data={coins:0,best:0,unlocked:['pulse'],car:'pulse',settings:{sound:true,music:false,graphics:'high'}}}return this.data},save(){localStorage.neonApex=JSON.stringify(this.data)}}; Store.load();
const Audio = {ctx:null,ensure(){if(!this.ctx) this.ctx=new (window.AudioContext||window.webkitAudioContext)()},tone(freq,duration=.08,type='sine',gain=.05){if(!Store.data.settings.sound)return;this.ensure();let o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+duration);o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+duration)},coin(){this.tone(770,.07,'sine',.07);setTimeout(()=>this.tone(1080,.1,'sine',.06),60)},crash(){this.tone(75,.28,'sawtooth',.15)},nitro(){this.tone(180,.12,'sawtooth',.04)},button(){this.tone(400,.04,'square',.03)}};
let W=0,H=0,dpr=1,last=0,activeScreen='mainMenu',selectedMode='endless',garageCar=Store.data.car;
let input={left:false,right:false,nitro:false,brake:false};
let game={running:false,paused:false,mode:'endless',time:0,score:0,distance:0,earned:0,speed:0,nitro:100,playerX:0,traffic:[],coins:[],powers:[],particles:[],spawn:0,coinSpawn:0,powerSpawn:0,boost:0,shield:0,mult:0,slow:0,shake:0,elapsed:0,nextDifficulty:0,finish:false};
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function show(id){screens.forEach(x=>x.classList.toggle('active',x.id===id));activeScreen=id;$('#hud').classList.toggle('hidden',id!=='playing');$('#mobileControls').classList.toggle('hidden',id!=='playing');if(id==='mainMenu')updateMenu()}
function updateMenu(){$('#bankCoins').textContent=Store.data.coins;$('#menuBest').textContent=Store.data.best.toLocaleString()}
function currentCar(){return CONFIG.cars.find(c=>c.id===Store.data.car)}
function road(){let top=H*.17,bottom=H*1.15;return {top,bottom,center:W/2,topW:Math.min(W*.15,140),bottomW:Math.min(W*.82,760)}}
function roadX(t,lane=0){let r=road(),w=r.topW+(r.bottomW-r.topW)*t;return r.center+lane*w*.235}
function addTraffic(){let lanes=[-1,0,1],lane=lanes[Math.floor(Math.random()*3)], types=['#ef426f','#f9a826','#7e6fff','#52d38b','#e9ebf4'];let y=-.1-Math.random()*.15;let safe=!game.traffic.some(o=>Math.abs(o.lane-lane)<.2&&Math.abs(o.y-y)<.23);if(safe)game.traffic.push({lane,y,color:types[Math.floor(Math.random()*types.length)],direction:'oncoming',speed:3.1,w:.11,h:.18})}
function addCoin(){let lane=[-1,0,1][Math.floor(Math.random()*3)];game.coins.push({lane,y:-.08,value:1,spin:0})}
function addPower(){let kinds=['nitro','shield','mult','slow'];game.powers.push({lane:[-1,0,1][Math.floor(Math.random()*3)],y:-.08,kind:kinds[Math.floor(Math.random()*4)],spin:0})}
function start(mode=selectedMode){Audio.ensure();let car=currentCar();game={...game,running:true,paused:false,mode,time:CONFIG.modes[mode].time||0,score:0,distance:0,earned:0,speed:car.speed*.45,nitro:100,playerX:0,traffic:[],coins:[],powers:[],particles:[],spawn:.8,coinSpawn:.4,powerSpawn:10,boost:0,shield:0,mult:0,slow:0,shake:0,elapsed:0,nextDifficulty:0,finish:false};show('playing');}
function end(reason='CRASHED'){if(!game.running)return;game.running=false;Store.data.coins+=game.earned;Store.data.best=Math.max(Store.data.best,Math.floor(game.score));Store.save();$('#resultTitle').textContent=reason==='TIME UP'?'TIME EXPIRED':reason==='CHALLENGE COMPLETE'?'CHALLENGE COMPLETE':'WRECKED';$('#resultHeading').textContent=reason==='CHALLENGE COMPLETE'?'YOU DID IT!':'RACE OVER';$('#finalScore').textContent=Math.floor(game.score).toLocaleString();$('#finalDistance').textContent=game.distance.toFixed(1)+' KM';$('#finalCoins').textContent='+'+game.earned;$('#finalBest').textContent=Store.data.best.toLocaleString();show('gameOver')}
function pause(){if(!game.running)return;game.paused=!game.paused;show(game.paused?'pauseMenu':'playing')}
function particle(x,y,color,count=12){for(let i=0;i<count;i++)game.particles.push({x,y,vx:(Math.random()-.5)*220,vy:(Math.random()-.5)*220,life:.4+Math.random()*.4,color})}
function update(dt){if(!game.running||game.paused)return;let car=currentCar(), diff=1+game.distance/5;game.elapsed+=dt;if(game.mode==='time'){game.time-=dt;if(game.time<=0){end('TIME UP');return}}if(input.left)game.playerX-=dt*(car.handling*0.23)*(game.speed/car.speed);if(input.right)game.playerX+=dt*(car.handling*0.23)*(game.speed/car.speed);game.playerX=Math.max(-1.28,Math.min(1.28,game.playerX));let target=car.speed*(game.boost>0?1.24:1);if(input.brake)target=car.speed*.34; if(input.nitro&&game.nitro>0){game.boost=.15;game.nitro=Math.max(0,game.nitro-dt*26);Audio.nitro()}else game.nitro=Math.min(100,game.nitro+dt*5);game.speed+=(target-game.speed)*dt*(car.accel*.65);game.boost=Math.max(0,game.boost-dt);game.shield=Math.max(0,game.shield-dt);game.mult=Math.max(0,game.mult-dt);game.slow=Math.max(0,game.slow-dt);let flow=game.speed/150*(game.slow?0.47:1);game.distance+=game.speed*dt/2400;game.score+=game.speed*dt*.48*(game.mult?2:1);game.spawn-=dt;if(game.spawn<=0){addTraffic();game.spawn=Math.max(.34,1.25-diff*.04)+Math.random()*.36}game.coinSpawn-=dt;if(game.coinSpawn<=0){addCoin();game.coinSpawn=.58+Math.random()*.55}game.powerSpawn-=dt;if(game.powerSpawn<=0){addPower();game.powerSpawn=9+Math.random()*8}game.traffic.forEach(o=>o.y+=dt*flow*(1.2-o.speed*.2));game.coins.forEach(o=>{o.y+=dt*flow;o.spin+=dt*8});game.powers.forEach(o=>{o.y+=dt*flow;o.spin+=dt*5});let hit=(o)=>o.y>.72&&o.y<.96&&Math.abs(o.lane-game.playerX)<.28;for(let o of game.traffic)if(hit(o)){if(game.shield){o.y=2;game.shield=0;particle(W/2,H*.82,'#78f7ff',22)}else{game.shake=.45;particle(W/2,H*.82,'#ff5a76',35);Audio.crash();end('CRASHED');return}}game.coins.forEach(o=>{if(hit(o)){o.y=2;let n=game.mult?2:1;game.earned+=n;game.score+=100*n;Audio.coin();particle(roadX(.85,game.playerX),H*.84,'#ffc94a',7)}});game.powers.forEach(o=>{if(hit(o)){o.y=2;if(o.kind==='nitro')game.nitro=100;if(o.kind==='shield')game.shield=7;if(o.kind==='mult')game.mult=9;if(o.kind==='slow')game.slow=6;game.score+=150;particle(roadX(.85,game.playerX),H*.84,'#fff',12)}});game.traffic=game.traffic.filter(o=>o.y<1.18);game.coins=game.coins.filter(o=>o.y<1.12);game.powers=game.powers.filter(o=>o.y<1.12);game.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});game.particles=game.particles.filter(p=>p.life>0);game.shake=Math.max(0,game.shake-dt);if(game.mode==='challenge'&&game.earned>=CONFIG.modes.challenge.coins)end('CHALLENGE COMPLETE')}
function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function carShape(x,y,w,h,color,player=false){ctx.save();ctx.translate(x,y);if(player&&game.boost){ctx.fillStyle='rgba(61,232,255,.45)';ctx.beginPath();ctx.ellipse(0,h*.7,w*.68,h*1.25,0,0,7);ctx.fill()}poly([[-w*.42,h*.45],[-w*.33,-h*.45],[-w*.16,-h*.65],[w*.16,-h*.65],[w*.33,-h*.45],[w*.42,h*.45],[w*.23,h*.6],[-w*.23,h*.6]],color);poly([[-w*.17,-h*.34],[w*.17,-h*.34],[w*.25,h*.12],[-w*.25,h*.12]],'#101a31');ctx.fillStyle='rgba(255,255,255,.82)';ctx.fillRect(-w*.26,-h*.56,w*.13,h*.07);ctx.fillRect(w*.13,-h*.56,w*.13,h*.07);ctx.fillStyle=player?'#ff3e89':'#ff4b5e';ctx.fillRect(-w*.26,h*.37,w*.13,h*.06);ctx.fillRect(w*.13,h*.37,w*.13,h*.06);ctx.restore()}
function draw(){let tr=CONFIG.tracks.city,r=road(),shake=game.shake?((Math.random()-.5)*game.shake*18):0;ctx.save();ctx.translate(shake,0);let sky=ctx.createLinearGradient(0,0,0,H*.6);sky.addColorStop(0,tr.sky);sky.addColorStop(1,'#16132a');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H); // skyline
ctx.fillStyle='#0a1024';for(let i=0;i<22;i++){let x=i*W/21+(i%2)*14,h=50+(i*43%130);ctx.fillRect(x,H*.2-h,W/18,h);if(i%2===0){ctx.fillStyle=tr.lights[i%tr.lights.length];ctx.globalAlpha=.25;ctx.fillRect(x+8,H*.2-h+14,3,h-20);ctx.globalAlpha=1;ctx.fillStyle='#0a1024'}}ctx.fillStyle=tr.ground;ctx.fillRect(0,r.top,W,H);poly([[r.center-r.topW,r.top],[r.center+r.topW,r.top],[r.center+r.bottomW,r.bottom],[r.center-r.bottomW,r.bottom]],'#252a39');for(let lane=-1;lane<=1;lane+=2){let a=roadX(0,lane*.5),b=roadX(1,lane*.5);ctx.strokeStyle='rgba(255,255,255,.7)';ctx.lineWidth=3;ctx.setLineDash([Math.max(8,(game.distance*100)%45),24]);ctx.beginPath();ctx.moveTo(a,r.top);ctx.lineTo(b,r.bottom);ctx.stroke()}ctx.setLineDash([]); // edge glow
for(let side of [-1,1]){ctx.strokeStyle=tr.lights[0];ctx.shadowBlur=10;ctx.shadowColor=tr.lights[0];ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(r.center+side*r.topW,r.top);ctx.lineTo(r.center+side*r.bottomW,r.bottom);ctx.stroke()}ctx.shadowBlur=0;
function pos(o){return {x:roadX(o.y,o.lane),y:r.top+(r.bottom-r.top)*o.y,scale:.22+o.y*.85}}
game.coins.forEach(o=>{let p=pos(o),rad=7*p.scale*1.8;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(o.spin);ctx.fillStyle='#ffc94a';ctx.shadowBlur=14;ctx.shadowColor='#ffc94a';ctx.beginPath();ctx.arc(0,0,rad,0,7);ctx.fill();ctx.fillStyle='#fff2b3';ctx.fillRect(-rad*.15,-rad*.5,rad*.3,rad);ctx.restore()});
game.powers.forEach(o=>{let p=pos(o),s=15*p.scale*1.5,icons={nitro:'N',shield:'S',mult:'Ã—2',slow:'â—·'};ctx.save();ctx.translate(p.x,p.y);ctx.rotate(o.spin);ctx.fillStyle={nitro:'#3de8ff',shield:'#86e9ff',mult:'#ffc94a',slow:'#c895ff'}[o.kind];ctx.shadowBlur=15;ctx.shadowColor=ctx.fillStyle;poly([[0,-s],[s,0],[0,s],[-s,0]],ctx.fillStyle);ctx.shadowBlur=0;ctx.fillStyle='#07101d';ctx.font=`bold ${Math.max(8,s*.8)}px Rajdhani`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(icons[o.kind],0,1);ctx.restore()});
game.traffic.sort((a,b)=>a.y-b.y).forEach(o=>{let p=pos(o);carShape(p.x,p.y,36*p.scale,65*p.scale,o.color)});let px=roadX(.86,game.playerX);carShape(px,H*.85,43,78,currentCar().color,true);if(game.shield){ctx.strokeStyle='#8bf5ff';ctx.lineWidth=3;ctx.shadowBlur=15;ctx.shadowColor='#8bf5ff';ctx.beginPath();ctx.ellipse(px,H*.85,36,56,0,0,7);ctx.stroke();ctx.shadowBlur=0}game.particles.forEach(p=>{ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3)});ctx.globalAlpha=1; if(game.boost){ctx.fillStyle='rgba(61,232,255,.08)';for(let i=0;i<18;i++)ctx.fillRect(Math.random()*W,H*.18+Math.random()*H*.75,2,35+Math.random()*90)}ctx.restore();if(game.mode==='time'){ctx.fillStyle='#fff';ctx.font='700 16px Rajdhani';ctx.textAlign='center';ctx.fillText('TIME '+Math.ceil(Math.max(0,game.time))+'s',W/2,35)}}
function renderHUD(){if(!game.running)return;$('#speedValue').textContent=Math.round(game.speed).toString().padStart(3,'0');$('#scoreValue').textContent=Math.floor(game.score).toLocaleString();$('#distanceValue').textContent=game.distance.toFixed(1);$('#coinsValue').textContent=game.earned;$('#nitroFill').style.width=game.nitro+'%';let obj='';if(game.mode==='challenge')obj='CHALLENGE: '+game.earned+'/'+CONFIG.modes.challenge.coins+' COINS';if(game.shield)obj='SHIELD '+Math.ceil(game.shield)+'s';else if(game.mult)obj='Ã—2 SCORE '+Math.ceil(game.mult)+'s';else if(game.slow)obj='SLOW TIME '+Math.ceil(game.slow)+'s';$('#objective').textContent=obj}
function frame(t){let dt=Math.min(.034,(t-last)/1000||0);last=t;update(dt);draw();renderHUD();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function renderGarage(){let car=CONFIG.cars.find(c=>c.id===garageCar),owned=Store.data.unlocked.includes(car.id);$('#carCards').innerHTML=CONFIG.cars.map(c=>`<button class="car-card ${c.id===garageCar?'selected':''}" data-car="${c.id}" style="--car:${c.color}"><i class="car-swatch"></i><b>${c.name}</b>${Store.data.unlocked.includes(c.id)?'<small>OWNED</small>':'<small class="lock">â—ˆ '+c.cost+'</small>'}</button>`).join('');$('#carDetails').innerHTML=`<h3 style="color:${car.color}">${car.name}</h3><p>${car.desc}</p><div class="bars">${[['TOP SPEED',car.speed/26],['ACCEL',car.accel],['HANDLING',car.handling],['BRAKING',car.brake]].map(([n,v])=>`<div class="barline"><span>${n}</span><div class="bar"><i style="width:${v*10}%"></i></div></div>`).join('')}</div>`;$('#carSelect').textContent=owned?(car.id===Store.data.car?'SELECTED':'SELECT CAR'):'UNLOCK Â· â—ˆ '+car.cost}
document.addEventListener('click',e=>{let a=e.target.closest('[data-action]');if(a){Audio.button();let x=a.dataset.action;if(x==='play'){selectedMode='endless';start()}if(x==='modes')show('modeMenu');if(x==='garage'){renderGarage();show('garageMenu')}if(x==='settings'){syncSettings();show('settingsMenu')}if(x==='menu'){game.running=false;show('mainMenu')}if(x==='restart')start(game.mode);if(x==='resume')pause()}let m=e.target.closest('[data-mode]');if(m){selectedMode=m.dataset.mode;document.querySelectorAll('.mode-card').forEach(x=>x.classList.toggle('selected',x===m))}if(e.target.id==='modeStart')start(selectedMode);let c=e.target.closest('[data-car]');if(c){garageCar=c.dataset.car;renderGarage()}if(e.target.id==='carSelect'){let car=CONFIG.cars.find(x=>x.id===garageCar);if(Store.data.unlocked.includes(car.id))Store.data.car=car.id;else if(Store.data.coins>=car.cost){Store.data.coins-=car.cost;Store.data.unlocked.push(car.id);Store.data.car=car.id;Store.save();Audio.coin()}renderGarage()}let set=e.target.closest('[data-setting]');if(set){let key=set.dataset.setting;Store.data.settings[key]=!Store.data.settings[key];Store.save();syncSettings()}});
function syncSettings(){document.querySelectorAll('[data-setting]').forEach(b=>b.classList.toggle('on',Store.data.settings[b.dataset.setting]));$('#graphics').value=Store.data.settings.graphics}$('#graphics').addEventListener('change',e=>{Store.data.settings.graphics=e.target.value;Store.save()});$('#pauseBtn').onclick=pause;
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowDown',' ','a','d','A','D','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape')pause();if(e.key==='ArrowLeft'||e.key==='a'||e.key==='A')input.left=true;if(e.key==='ArrowRight'||e.key==='d'||e.key==='D')input.right=true;if(e.key==='ArrowDown'||e.key==='s'||e.key==='S')input.brake=true;if(e.key===' ')input.nitro=true});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a'||e.key==='A')input.left=false;if(e.key==='ArrowRight'||e.key==='d'||e.key==='D')input.right=false;if(e.key==='ArrowDown'||e.key==='s'||e.key==='S')input.brake=false;if(e.key===' ')input.nitro=false});document.querySelectorAll('[data-control]').forEach(b=>{let key=b.dataset.control;let down=e=>{e.preventDefault();input[key]=true};let up=e=>{e.preventDefault();input[key]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)});
updateMenu();

